export const HISTORY = [
  {
    id: 1, 
    type: "transfer", // transfer, payment, income, withdrawal, topup (перевод, оплата, доход, снятие средств, пополнение счета)
    amount: 2000.00,
    currency: "RUB",
    title: "Алексей Иванов",
    description: "Алексей И. · •• 1234",
    date: "2025-08-01T13:24:00",
    status: "success",
    category: "Входящий перевод",
    cardId: 2,
    attempt: false
  },
  {
    id: 2,
    type: "payment",
    amount: -599.00,
    currency: "RUB",
    title: "Spotify",
    description: "Ежемесячная подписка",
    date: "2025-07-29T08:15:00",
    status: "success",
    category: "Подписки",
    cardId: 2,
    attempt: false
  },
  {
    id: 3,
    type: "topup",
    amount: 10000.00,
    currency: "RUB",
    title: "Пополнение",
    description: "Счёт пополнен через СБП",
    date: "2025-07-25T17:05:00",
    status: "success",
    category: "Пополнения",
    cardId: 2,
    attempt: true
  },
  {
    id: 4,
    type: "payment",
    amount: -1349.00,
    currency: "RUB",
    title: "Ozon",
    description: "Покупка на маркетплейсе",
    date: "2025-07-24T11:33:00",
    status: "success",
    category: "Покупки",
    cardId: 2,
    attempt: true
  },
  {
    id: 5,
    type: "transfer",
    amount: -5000.55,
    currency: "RUB",
    title: "Михаил Сергеев",
    description: "Михаил С. · •• 8721",
    date: "2025-07-22T14:50:00",
    status: "pending",
    category: "Исходящий перевод",
    cardId: 1,
    attempt: true
  },
  {
    id: 6,
    type: "income",
    amount: 45000,
    currency: "RUB",
    title: "Зарплата",
    description: "ООО Технострой",
    date: "2025-07-20T09:00:00",
    status: "success",
    category: "Доходы",
    cardId: 2,
    attempt: true
  },
  {
    id: 7,
    type: "withdrawal",
    amount: -7000,
    currency: "RUB",
    title: "Снятие наличных",
    description: "Банкомат Сбербанк · Москва",
    date: "2025-07-19T18:20:00",
    status: "success",
    category: "Снятие",
    cardId: 1,
    attempt: true
  },
  {
    id: 8,
    type: "payment",
    amount: -239,
    currency: "RUB",
    title: "YouTube Premium",
    description: "Подписка Google",
    date: "2025-07-17T07:30:00",
    status: "success",
    category: "Подписки",
    cardId: 2,
    attempt: true
  },
  {
    id: 9,
    type: "topup",
    amount: 3000,
    currency: "RUB",
    title: "Пополнение",
    description: "Пополнение с Тинькофф",
    date: "2025-06-15T12:44:00",
    status: "success",
    category: "Пополнения",
    cardId: 1,
    attempt: true
  },
  {
    id: 10,
    type: "payment",
    amount: -890,
    currency: "RUB",
    title: "Пятёрочка",
    description: "Покупка продуктов",
    date: "2025-06-13T19:15:00",
    status: "success",
    category: "Продукты",
    cardId: 2,
    attempt: true
  }
];
